version: '3'

services: 
  backend:
    restart: always
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile-dev
    volumes: 
      - '.:/user/src/app/.'
    ports:
      - 5000:5000
    extra_hosts:
      - "ahmed.sentry:${MACHINE_IP}"
    environment: 
      - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DSN=http://df4d5d3067a54b58881cc52a9fd7c13c@ahmed.sentry:9000/2